name: CI

on: push

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
        gemfile:
          - rails6.0
          - rails6.1
          - rails7.0
          - rails7.1
        include:
          - {ruby-version: '2.7', gemfile: rails5.2}
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      - uses: zendesk/checkout@v4
      - name: Set up Ruby
        uses: zendesk/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - run: bundle install
      - name: Tests
        run: bundle exec rake test

  linter:
    runs-on: ubuntu-latest
    name: Linting of Ruby files
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec rake standard
