name: Test against Rails main

on:
  schedule:
    - cron: "0 0 * * *" # Run every day at 00:00 UTC
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - '3.4'
        gemfile:
          - rails_main
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      - uses: zendesk/checkout@v4
      - name: Set up Ruby
        uses: zendesk/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - run: bundle install
      - name: Tests
        run: bundle exec rake test
